### ISSUE TITLE
issue with building and running the benchmark utility

### ISSUE THREAD

**Issue by rahul-thube** [aerospike/aerospike-benchmark#57]
hi 

i am facing issue while building and executing this benchmark utility.
can someone please advise on this issue, am i missing any step?

++++++++++++
[airun@N2VL-TA-AIA09 aerospike-benchmark]$ make
### Makefile:6: *** Please set the CLIENTREPO environment variable.  Stop.
[airun@N2VL-TA-AIA09 aerospike-benchmark]$ pwd
/data/landing/benchmark/aerospike-benchmark
[airun@N2VL-TA-AIA09 aerospike-benchmark]$ export CLIENTREPO=/data/landing/benchmark/aerospike-benchmark

[airun@N2VL-TA-AIA09 aerospike-benchmark]$ make
mkdir target
mkdir target/obj
cc -std=gnu99 -Wall -fPIC -O3 -MMD -MP -fno-common -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_GNU_SOURCE -march=nocona -rdynamic -I/data/landing/benchmark/aerospike-benchmark/src/include -I/data/landing/benchmark/aerospike-benchmark/modules -I/data/landing/benchmark/aerospike-benchmark/modules/libcyaml/include -I/data/landing/benchmark/aerospike-benchmark/src/include -I/data/landing/benchmark/aerospike-benchmark/modules/common/src/include -I/data/landing/benchmark/aerospike-benchmark/modules/mod-lua/src/include -I/data/landing/benchmark/aerospike-benchmark/modules/base/src/include  -I/usr/local/include -flto -o target/obj/main.o -c src/main/main.c -I/data/landing/benchmark/aerospike-benchmark/src/include -I/data/landing/benchmark/aerospike-benchmark/modules -I/data/landing/benchmark/aerospike-benchmark/modules/libcyaml/include -I/data/landing/benchmark/aerospike-benchmark/src/include -I/data/landing/benchmark/aerospike-benchmark/modules/common/src/include -I/data/landing/benchmark/aerospike-benchmark/modules/mod-lua/src/include -I/data/landing/benchmark/aerospike-benchmark/modules/base/src/include
cc -std=gnu99 -Wall -fPIC -O3 -MMD -MP -fno-common -fno-strict-aliasing -D_FILE_OFFSET_BITS=64 -D_REENTRANT -D_GNU_SOURCE -march=nocona -rdynamic -I/data/landing/benchmark/aerospike-benchmark/src/include -I/data/landing/benchmark/aerospike-benchmark/modules -I/data/landing/benchmark/aerospike-benchmark/modules/libcyaml/include -I/data/landing/benchmark/aerospike-benchmark/src/include -I/data/landing/benchmark/aerospike-benchmark/modules/common/src/include -I/data/landing/benchmark/aerospike-benchmark/modules/mod-lua/src/include -I/data/landing/benchmark/aerospike-benchmark/modules/base/src/include  -I/usr/local/include -flto -o target/obj/benchmark.o -c src/main/benchmark.c -I/data/landing/benchmark/aerospike-benchmark/src/include -I/data/landing/benchmark/aerospike-benchmark/modules -I/data/landing/benchmark/aerospike-benchmark/modules/libcyaml/include -I/data/landing/benchmark/aerospike-benchmark/src/include -I/data/landing/benchmark/aerospike-benchmark/modules/common/src/include -I/data/landing/benchmark/aerospike-benchmark/modules/mod-lua/src/include -I/data/landing/benchmark/aerospike-benchmark/modules/base/src/include
### In file included from src/main/benchmark.c:39:0:
/data/landing/benchmark/aerospike-benchmark/src/include/benchmark.h:45:16: error: ‘AS_PASSWORD_SIZE’ undeclared here (not in a function)
  char password[AS_PASSWORD_SIZE];
                ^
/data/landing/benchmark/aerospike-benchmark/src/include/benchmark.h:80:2: error: unknown type name ‘as_policy_read_mode_ap’
  as_policy_read_mode_ap read_mode_ap;
  ^
/data/landing/benchmark/aerospike-benchmark/src/include/benchmark.h:81:2: error: unknown type name ‘as_policy_read_mode_sc’
  as_policy_read_mode_sc read_mode_sc;
  ^
/data/landing/benchmark/aerospike-benchmark/src/include/benchmark.h:89:2: error: unknown type name ‘as_auth_mode’
  as_auth_mode auth_mode;
  ^
src/main/benchmark.c: In function ‘connect_to_server’:
src/main/benchmark.c:201:5: error: ‘as_config’ has no member named ‘login_timeout_ms’
  cfg.login_timeout_ms = 10000;
     ^
src/main/benchmark.c:217:14: error: ‘as_policy_base’ has no member named ‘compress’
  p->read.base.compress = args->enable_compression;
              ^
src/main/benchmark.c:219:9: error: ‘as_policy_read’ has no member named ‘read_mode_ap’
  p->read.read_mode_ap = args->read_mode_ap;
         ^
src/main/benchmark.c:220:9: error: ‘as_policy_read’ has no member named ‘read_mode_sc’
  p->read.read_mode_sc = args->read_mode_sc;
         ^
src/main/benchmark.c:225:15: error: ‘as_policy_base’ has no member named ‘compress’
  p->write.base.compress = args->enable_compression;
               ^
src/main/benchmark.c:233:17: error: ‘as_policy_base’ has no member named ‘compress’
  p->operate.base.compress = args->enable_compression;
                 ^
src/main/benchmark.c:237:12: error: ‘as_policy_operate’ has no member named ‘read_mode_ap’
  p->operate.read_mode_ap = args->read_mode_ap;
            ^
src/main/benchmark.c:238:12: error: ‘as_policy_operate’ has no member named ‘read_mode_sc’
  p->operate.read_mode_sc = args->read_mode_sc;
            ^
src/main/benchmark.c:243:16: error: ‘as_policy_base’ has no member named ‘compress’
  p->remove.base.compress = args->enable_compression;
                ^
src/main/benchmark.c:251:15: error: ‘as_policy_base’ has no member named ‘compress’
  p->batch.base.compress = args->enable_compression;
               ^
src/main/benchmark.c:252:10: error: ‘as_policy_batch’ has no member named ‘replica’
  p->batch.replica = args->replica;
          ^
src/main/benchmark.c:253:10: error: ‘as_policy_batch’ has no member named ‘read_mode_ap’
  p->batch.read_mode_ap = args->read_mode_ap;
          ^
src/main/benchmark.c:254:10: error: ‘as_policy_batch’ has no member named ‘read_mode_sc’
  p->batch.read_mode_sc = args->read_mode_sc;
          ^
src/main/benchmark.c:260:5: error: ‘as_config’ has no member named ‘auth_mode’
  cfg.auth_mode = args->auth_mode;
     ^
src/main/benchmark.c: In function ‘_run’:
src/main/benchmark.c:442:4: warning: implicit declaration of function ‘as_store_uint8’ [-Wimplicit-function-declaration]
    as_store_uint8((uint8_t*) &tdatas[i]->finished, true);
    ^
make: *** [target/obj/benchmark.o] Error 1
++++++++++++++++++++++

**Comment by dwelch-spike** [comment]
Asbench has changed quite a bit since this issue was posted. It is no longer recommended to set CLIENTREPO. Instead, asbench will build using the c client under `modules/c-client` by default.

I'll post a few thoughts about what might have been happening though. It looks like `export CLIENTREPO=/data/landing/benchmark/aerospike-benchmark` did not contain the right version of the C client, it was lacking features like compression on as_policy_base, etc.

Sorry this issues was never addressed, if it is still a problem please try upgrading the tool or opening another issue.
